// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxfmhruxybcgjeufnyvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4Zm1ocnV4eWJjZ2pldWZueXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDE5MzAsImV4cCI6MjA2MzE3NzkzMH0.pOU0d6D9EhHeko-RV5qSzBih0BsJXaSz6M5vVjk2QeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);